# 식품의 정보를 담은 FOOD_PRODUCT
# 식품의 주문 정보를 담은 FOOD_ORDER

SELECT 
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    SUM(p.PRICE * o.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT p
JOIN FOOD_ORDER o
ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE YEAR(o.PRODUCE_DATE) = 2022 AND MONTH(o.PRODUCE_DATE) = 5
GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, p.PRODUCT_ID ASC;