SELECT f.FLAVOR
FROM FIRST_HALF f
JOIN JULY j
ON f.FLAVOR = j.FLAVOR
GROUP BY f.FLAVOR, f.TOTAL_ORDER
ORDER BY f.TOTAL_ORDER + SUM(j.TOTAL_ORDER) DESC
LIMIT 3;


# SELECT FLAVOR
# FROM (
#     SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF
#     UNION ALL
#     SELECT FLAVOR, TOTAL_ORDER FROM JULY
# ) T
# GROUP BY FLAVOR
# ORDER BY SUM(TOTAL_ORDER) DESC
# LIMIT 3;