SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT ITEM_ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IN (
        SELECT ITEM_ID
        FROM ITEM_INFO
        WHERE RARITY = 'RARE'
    )
)
ORDER BY ITEM_ID DESC;




# ITEM_INFO에서 RARITY = 'RARE'인 ITEM_ID 추출
# 해당 ITEM_ID를 PARENT_ITEM_ID로 갖는 ITEM_TREE의 ITEM_ID 추출
# 해당 ITEM_ID들로 ITEM_INFO에서 데이터 조회