SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')
   OR SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')
ORDER BY ID;




# SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
# FROM DEVELOPERS D
# WHERE EXISTS (
#   SELECT 1
#   FROM SKILLCODES S
#   WHERE S.NAME IN ('Python', 'C#')
#     AND (D.SKILL_CODE & S.CODE) != 0
# )
# ORDER BY D.ID;