# 연도별로 그룹화하여 각 연도와 가장 큰 대장균의 크기를 구함
# ECOLI_DATA와 위의 테이블을 조인하여 결과 구함

SELECT 
    YEAR(e.DIFFERENTIATION_DATE) AS YEAR,
    m.max_size - e.SIZE_OF_COLONY AS YEAR_DEV,
    e.ID
FROM ECOLI_DATA e
JOIN (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS max_size
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) m
ON YEAR(e.DIFFERENTIATION_DATE) = m.YEAR
ORDER BY YEAR, YEAR_DEV;